- name: directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ directories_default }} + {{ directories }}"

- name: files
  copy:
    src: "{{ item }}"
    dest: "{{ workdir }}/{{ item }}"
    mode: '0644'
  loop:
    - "{{ files_default }} + {{ files }}"

- name: "check {{ pre_deploy_script_name }}"
  stat:
    path: "{{ workdir }}/deploy.pre.sh"
  register: pre_deploy

- name: "check {{ post_deploy_script_name }}"
  stat:
    path: "{{ workdir }}/deploy.post.sh"
  register: post_deploy
