- name: directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ deploy_directories_default }} + {{ deploy_directories }}"

- name: files
  copy:
    src: "{{ item }}"
    dest: "{{ deploy_workdir }}/{{ item }}"
    mode: '0644'
  loop: "{{ deploy_files_default }} + {{ deploy_files }}"

- name: "check {{ deploy_pre_deploy_script_name }}"
  stat:
    path: "{{ deploy_workdir }}/{{ deploy_pre_deploy_script_name }}"
  register: pre_deploy

- name: "check {{ deploy_post_deploy_script_name }}"
  stat:
    path: "{{ deploy_workdir }}/{{ deploy_post_deploy_script_name }}"
  register: post_deploy
