- name: "run {{ deploy_pre_deploy_script_name }}"
  shell:
    cmd: "bash {{ deploy_pre_deploy_script_name }}"
    chdir: "{{ deploy_workdir }}"
  when: pre_deploy.stat.exists

- name: start deployment
  community.docker.docker_compose:
    project_src: "{{ deploy_workdir }}"
    env_file: "{{ deploy_env_file | default(None) }}"
    scale: "{{ deploy_scale }}"
    remove_orphans: "{{ deploy_remove_orphans }}"
    pull: "{{ deploy_docker_pull }}"

- name: "run {{ deploy_post_deploy_script_name }}"
  shell:
    cmd: "bash {{ deploy_post_deploy_script_name }}"
    chdir: "{{ deploy_workdir }}"
  when: post_deploy.stat.exists
