- name: "run {{ pre_deploy_script_name }}"
  shell:
    cmd: "bash {{ pre_deploy_script_name }}"
    chdir: "{{ workdir }}"
  when: pre_deploy.stat.exists

- name: start deployment
  community.docker.docker_compose:
    project_src: "{{ workdir }}"
    env_file: "{{ env_file | default(None) }}"
    scale: "{{ scale | default(None) }}"

- name: "run {{ post_deploy_script_name }}"
  shell:
    cmd: "bash {{ post_deploy_script_name }}"
    chdir: "{{ workdir }}"
  when: post_deploy.stat.exists
